//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MyDbEntities : DbContext
    {
        public MyDbEntities()
            : base("name=MyDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<AOH_ForumTopic> AOH_ForumTopic { get; set; }
        public DbSet<AOH_JoinWelfare> AOH_JoinWelfare { get; set; }
        public DbSet<AOH_SeckillingWinner> AOH_SeckillingWinner { get; set; }
        public DbSet<AOH_Welfare> AOH_Welfare { get; set; }
        public DbSet<numbers> numbers { get; set; }
    }
}
