//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ebuy.Ask.Filter.ServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Ask.Filter.ServiceReference.ServiceSoap")]
    public interface ServiceSoap {
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 message 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReceiveMessage", ReplyAction="*")]
        Ebuy.Ask.Filter.ServiceReference.ReceiveMessageResponse ReceiveMessage(Ebuy.Ask.Filter.ServiceReference.ReceiveMessageRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReceiveMessage", ReplyAction="*")]
        System.Threading.Tasks.Task<Ebuy.Ask.Filter.ServiceReference.ReceiveMessageResponse> ReceiveMessageAsync(Ebuy.Ask.Filter.ServiceReference.ReceiveMessageRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReceiveMessageRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReceiveMessage", Namespace="http://tempuri.org/", Order=0)]
        public Ebuy.Ask.Filter.ServiceReference.ReceiveMessageRequestBody Body;
        
        public ReceiveMessageRequest() {
        }
        
        public ReceiveMessageRequest(Ebuy.Ask.Filter.ServiceReference.ReceiveMessageRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ReceiveMessageRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string message;
        
        public ReceiveMessageRequestBody() {
        }
        
        public ReceiveMessageRequestBody(string message) {
            this.message = message;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReceiveMessageResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReceiveMessageResponse", Namespace="http://tempuri.org/", Order=0)]
        public Ebuy.Ask.Filter.ServiceReference.ReceiveMessageResponseBody Body;
        
        public ReceiveMessageResponse() {
        }
        
        public ReceiveMessageResponse(Ebuy.Ask.Filter.ServiceReference.ReceiveMessageResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ReceiveMessageResponseBody {
        
        public ReceiveMessageResponseBody() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiceSoapChannel : Ebuy.Ask.Filter.ServiceReference.ServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceSoapClient : System.ServiceModel.ClientBase<Ebuy.Ask.Filter.ServiceReference.ServiceSoap>, Ebuy.Ask.Filter.ServiceReference.ServiceSoap {
        
        public ServiceSoapClient() {
        }
        
        public ServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Ebuy.Ask.Filter.ServiceReference.ReceiveMessageResponse Ebuy.Ask.Filter.ServiceReference.ServiceSoap.ReceiveMessage(Ebuy.Ask.Filter.ServiceReference.ReceiveMessageRequest request) {
            return base.Channel.ReceiveMessage(request);
        }
        
        public void ReceiveMessage(string message) {
            Ebuy.Ask.Filter.ServiceReference.ReceiveMessageRequest inValue = new Ebuy.Ask.Filter.ServiceReference.ReceiveMessageRequest();
            inValue.Body = new Ebuy.Ask.Filter.ServiceReference.ReceiveMessageRequestBody();
            inValue.Body.message = message;
            Ebuy.Ask.Filter.ServiceReference.ReceiveMessageResponse retVal = ((Ebuy.Ask.Filter.ServiceReference.ServiceSoap)(this)).ReceiveMessage(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Ebuy.Ask.Filter.ServiceReference.ReceiveMessageResponse> Ebuy.Ask.Filter.ServiceReference.ServiceSoap.ReceiveMessageAsync(Ebuy.Ask.Filter.ServiceReference.ReceiveMessageRequest request) {
            return base.Channel.ReceiveMessageAsync(request);
        }
        
        public System.Threading.Tasks.Task<Ebuy.Ask.Filter.ServiceReference.ReceiveMessageResponse> ReceiveMessageAsync(string message) {
            Ebuy.Ask.Filter.ServiceReference.ReceiveMessageRequest inValue = new Ebuy.Ask.Filter.ServiceReference.ReceiveMessageRequest();
            inValue.Body = new Ebuy.Ask.Filter.ServiceReference.ReceiveMessageRequestBody();
            inValue.Body.message = message;
            return ((Ebuy.Ask.Filter.ServiceReference.ServiceSoap)(this)).ReceiveMessageAsync(inValue);
        }
    }
}
