//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ebuy.Data.Zhidao.ServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://data.zhidao.yiche.com/", ConfigurationName="Data.Zhidao.ServiceReference.AskUGCSyncServiceSoap")]
    public interface AskUGCSyncServiceSoap {
        
        // CODEGEN: 命名空间 http://data.zhidao.yiche.com/ 的元素名称 xmlMessage 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://data.zhidao.yiche.com/ReceiveMessage", ReplyAction="*")]
        Ebuy.Data.Zhidao.ServiceReference.ReceiveMessageResponse ReceiveMessage(Ebuy.Data.Zhidao.ServiceReference.ReceiveMessageRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://data.zhidao.yiche.com/ReceiveMessage", ReplyAction="*")]
        System.Threading.Tasks.Task<Ebuy.Data.Zhidao.ServiceReference.ReceiveMessageResponse> ReceiveMessageAsync(Ebuy.Data.Zhidao.ServiceReference.ReceiveMessageRequest request);
        
        // CODEGEN: 命名空间 http://data.zhidao.yiche.com/ 的元素名称 entityType 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://data.zhidao.yiche.com/GetUGCSyncEntityInfo", ReplyAction="*")]
        Ebuy.Data.Zhidao.ServiceReference.GetUGCSyncEntityInfoResponse GetUGCSyncEntityInfo(Ebuy.Data.Zhidao.ServiceReference.GetUGCSyncEntityInfoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://data.zhidao.yiche.com/GetUGCSyncEntityInfo", ReplyAction="*")]
        System.Threading.Tasks.Task<Ebuy.Data.Zhidao.ServiceReference.GetUGCSyncEntityInfoResponse> GetUGCSyncEntityInfoAsync(Ebuy.Data.Zhidao.ServiceReference.GetUGCSyncEntityInfoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReceiveMessageRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReceiveMessage", Namespace="http://data.zhidao.yiche.com/", Order=0)]
        public Ebuy.Data.Zhidao.ServiceReference.ReceiveMessageRequestBody Body;
        
        public ReceiveMessageRequest() {
        }
        
        public ReceiveMessageRequest(Ebuy.Data.Zhidao.ServiceReference.ReceiveMessageRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://data.zhidao.yiche.com/")]
    public partial class ReceiveMessageRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string xmlMessage;
        
        public ReceiveMessageRequestBody() {
        }
        
        public ReceiveMessageRequestBody(string xmlMessage) {
            this.xmlMessage = xmlMessage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReceiveMessageResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReceiveMessageResponse", Namespace="http://data.zhidao.yiche.com/", Order=0)]
        public Ebuy.Data.Zhidao.ServiceReference.ReceiveMessageResponseBody Body;
        
        public ReceiveMessageResponse() {
        }
        
        public ReceiveMessageResponse(Ebuy.Data.Zhidao.ServiceReference.ReceiveMessageResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ReceiveMessageResponseBody {
        
        public ReceiveMessageResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUGCSyncEntityInfoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUGCSyncEntityInfo", Namespace="http://data.zhidao.yiche.com/", Order=0)]
        public Ebuy.Data.Zhidao.ServiceReference.GetUGCSyncEntityInfoRequestBody Body;
        
        public GetUGCSyncEntityInfoRequest() {
        }
        
        public GetUGCSyncEntityInfoRequest(Ebuy.Data.Zhidao.ServiceReference.GetUGCSyncEntityInfoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://data.zhidao.yiche.com/")]
    public partial class GetUGCSyncEntityInfoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int appId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string entityType;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string entityGuid;
        
        public GetUGCSyncEntityInfoRequestBody() {
        }
        
        public GetUGCSyncEntityInfoRequestBody(int appId, string entityType, string entityGuid) {
            this.appId = appId;
            this.entityType = entityType;
            this.entityGuid = entityGuid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUGCSyncEntityInfoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUGCSyncEntityInfoResponse", Namespace="http://data.zhidao.yiche.com/", Order=0)]
        public Ebuy.Data.Zhidao.ServiceReference.GetUGCSyncEntityInfoResponseBody Body;
        
        public GetUGCSyncEntityInfoResponse() {
        }
        
        public GetUGCSyncEntityInfoResponse(Ebuy.Data.Zhidao.ServiceReference.GetUGCSyncEntityInfoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://data.zhidao.yiche.com/")]
    public partial class GetUGCSyncEntityInfoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetUGCSyncEntityInfoResult;
        
        public GetUGCSyncEntityInfoResponseBody() {
        }
        
        public GetUGCSyncEntityInfoResponseBody(string GetUGCSyncEntityInfoResult) {
            this.GetUGCSyncEntityInfoResult = GetUGCSyncEntityInfoResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AskUGCSyncServiceSoapChannel : Ebuy.Data.Zhidao.ServiceReference.AskUGCSyncServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AskUGCSyncServiceSoapClient : System.ServiceModel.ClientBase<Ebuy.Data.Zhidao.ServiceReference.AskUGCSyncServiceSoap>, Ebuy.Data.Zhidao.ServiceReference.AskUGCSyncServiceSoap {
        
        public AskUGCSyncServiceSoapClient() {
        }
        
        public AskUGCSyncServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AskUGCSyncServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AskUGCSyncServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AskUGCSyncServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Ebuy.Data.Zhidao.ServiceReference.ReceiveMessageResponse Ebuy.Data.Zhidao.ServiceReference.AskUGCSyncServiceSoap.ReceiveMessage(Ebuy.Data.Zhidao.ServiceReference.ReceiveMessageRequest request) {
            return base.Channel.ReceiveMessage(request);
        }
        
        public void ReceiveMessage(string xmlMessage) {
            Ebuy.Data.Zhidao.ServiceReference.ReceiveMessageRequest inValue = new Ebuy.Data.Zhidao.ServiceReference.ReceiveMessageRequest();
            inValue.Body = new Ebuy.Data.Zhidao.ServiceReference.ReceiveMessageRequestBody();
            inValue.Body.xmlMessage = xmlMessage;
            Ebuy.Data.Zhidao.ServiceReference.ReceiveMessageResponse retVal = ((Ebuy.Data.Zhidao.ServiceReference.AskUGCSyncServiceSoap)(this)).ReceiveMessage(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Ebuy.Data.Zhidao.ServiceReference.ReceiveMessageResponse> Ebuy.Data.Zhidao.ServiceReference.AskUGCSyncServiceSoap.ReceiveMessageAsync(Ebuy.Data.Zhidao.ServiceReference.ReceiveMessageRequest request) {
            return base.Channel.ReceiveMessageAsync(request);
        }
        
        public System.Threading.Tasks.Task<Ebuy.Data.Zhidao.ServiceReference.ReceiveMessageResponse> ReceiveMessageAsync(string xmlMessage) {
            Ebuy.Data.Zhidao.ServiceReference.ReceiveMessageRequest inValue = new Ebuy.Data.Zhidao.ServiceReference.ReceiveMessageRequest();
            inValue.Body = new Ebuy.Data.Zhidao.ServiceReference.ReceiveMessageRequestBody();
            inValue.Body.xmlMessage = xmlMessage;
            return ((Ebuy.Data.Zhidao.ServiceReference.AskUGCSyncServiceSoap)(this)).ReceiveMessageAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Ebuy.Data.Zhidao.ServiceReference.GetUGCSyncEntityInfoResponse Ebuy.Data.Zhidao.ServiceReference.AskUGCSyncServiceSoap.GetUGCSyncEntityInfo(Ebuy.Data.Zhidao.ServiceReference.GetUGCSyncEntityInfoRequest request) {
            return base.Channel.GetUGCSyncEntityInfo(request);
        }
        
        public string GetUGCSyncEntityInfo(int appId, string entityType, string entityGuid) {
            Ebuy.Data.Zhidao.ServiceReference.GetUGCSyncEntityInfoRequest inValue = new Ebuy.Data.Zhidao.ServiceReference.GetUGCSyncEntityInfoRequest();
            inValue.Body = new Ebuy.Data.Zhidao.ServiceReference.GetUGCSyncEntityInfoRequestBody();
            inValue.Body.appId = appId;
            inValue.Body.entityType = entityType;
            inValue.Body.entityGuid = entityGuid;
            Ebuy.Data.Zhidao.ServiceReference.GetUGCSyncEntityInfoResponse retVal = ((Ebuy.Data.Zhidao.ServiceReference.AskUGCSyncServiceSoap)(this)).GetUGCSyncEntityInfo(inValue);
            return retVal.Body.GetUGCSyncEntityInfoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Ebuy.Data.Zhidao.ServiceReference.GetUGCSyncEntityInfoResponse> Ebuy.Data.Zhidao.ServiceReference.AskUGCSyncServiceSoap.GetUGCSyncEntityInfoAsync(Ebuy.Data.Zhidao.ServiceReference.GetUGCSyncEntityInfoRequest request) {
            return base.Channel.GetUGCSyncEntityInfoAsync(request);
        }
        
        public System.Threading.Tasks.Task<Ebuy.Data.Zhidao.ServiceReference.GetUGCSyncEntityInfoResponse> GetUGCSyncEntityInfoAsync(int appId, string entityType, string entityGuid) {
            Ebuy.Data.Zhidao.ServiceReference.GetUGCSyncEntityInfoRequest inValue = new Ebuy.Data.Zhidao.ServiceReference.GetUGCSyncEntityInfoRequest();
            inValue.Body = new Ebuy.Data.Zhidao.ServiceReference.GetUGCSyncEntityInfoRequestBody();
            inValue.Body.appId = appId;
            inValue.Body.entityType = entityType;
            inValue.Body.entityGuid = entityGuid;
            return ((Ebuy.Data.Zhidao.ServiceReference.AskUGCSyncServiceSoap)(this)).GetUGCSyncEntityInfoAsync(inValue);
        }
    }
}
